version: "3.7"

services:
  db:
    container_name: mongo-db
    image: mongo
    networks:
      - mongo-compose-network
    ports:
      - '27017:27017'
    volumes:
      - ./data:/data/db1
  mongo-express:
    container_name: mongo-expresss
    image: mongo-express
    depends_on:
      - db
    networks:
      - mongo-compose-network
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo-db
    ports:
      - '8081:8081'
    volumes:
      - ./data:/data/db

networks:
  mongo-compose-network:
    driver: bridge


